import type { PricingItem } from "@/content/types";

export const pricingItems: PricingItem[] = [
  {
    slug: "one-on-one-single",
    name: "Single One-on-One Session",
    description: "Focused private coaching session inside the appointment-only studio.",
    amount: 1000,
    unit: "45 min",
    type: "one-time",
    idealFor: "First-time clients, travellers, and clients wanting flexible sessions.",
    features: [
      "Private gym in a home residence",
      "Technique, posture, and strength guidance",
      "WhatsApp follow-up after session",
    ],
    serviceSlug: "private-personal-training",
  },
  {
    slug: "one-on-one-4",
    name: "4-Session Pack",
    description: "A strong starter package for building routine and momentum.",
    amount: 3800,
    unit: "4 x 45 min",
    badge: "Starter",
    type: "package",
    idealFor: "Busy professionals who want a structured first month.",
    features: [
      "Private assessment and movement screen",
      "Four scheduled sessions",
      "Goal tracking and WhatsApp accountability",
    ],
    serviceSlug: "private-personal-training",
  },
  {
    slug: "one-on-one-8",
    name: "8-Session Pack",
    description: "Consistent coaching for visible changes in strength, shape, and confidence.",
    amount: 7200,
    unit: "8 x 45 min",
    badge: "Most Popular",
    type: "package",
    idealFor: "Clients wanting momentum without compromising privacy.",
    features: [
      "Program progression across eight sessions",
      "Technique refinement and progression planning",
      "Nutrition and habit support",
    ],
    serviceSlug: "private-personal-training",
  },
  {
    slug: "one-on-one-12",
    name: "12-Session Pack",
    description: "Premium transformation cadence with deeper accountability and progress review.",
    amount: 10200,
    unit: "12 x 45 min",
    badge: "Best Value",
    type: "package",
    idealFor: "Clients committed to a high-touch private coaching block.",
    features: [
      "Structured progression roadmap",
      "Lifestyle and schedule adjustment support",
      "Priority WhatsApp check-ins",
    ],
    serviceSlug: "private-personal-training",
  },
  {
    slug: "couple-single",
    name: "Couple Session",
    description: "Private premium session for couples or friends training together.",
    amount: 1500,
    unit: "45 min",
    type: "one-time",
    idealFor: "Couples, friends, or training partners who want shared accountability.",
    features: [
      "Two-person coaching in complete privacy",
      "Balanced progressions for both clients",
      "Coordinated scheduling and support",
    ],
    serviceSlug: "couple-training",
  },
  {
    slug: "couple-package",
    name: "Couple Package",
    description: "Eight guided sessions designed to keep two people progressing together.",
    amount: 10800,
    unit: "8 x 45 min",
    badge: "Shared Value",
    type: "package",
    idealFor: "Couples wanting consistency, fun, and accountability.",
    features: [
      "Eight premium private sessions",
      "Joint progress tracking",
      "WhatsApp support between visits",
    ],
    serviceSlug: "couple-training",
  },
  {
    slug: "house-call-single",
    name: "House Call Session",
    description: "Professional coaching delivered to your home, villa, or private residence.",
    amount: 2000,
    unit: "45 min",
    type: "one-time",
    idealFor: "Clients who prefer maximum convenience and privacy.",
    features: [
      "Travel to your location by arrangement",
      "Portable coaching format tailored to your space",
      "Availability confirmation via WhatsApp",
    ],
    serviceSlug: "house-calls",
  },
  {
    slug: "online-coaching-monthly",
    name: "Online Coaching Monthly",
    description: "Remote coaching subscription with programming, feedback, and WhatsApp accountability.",
    amount: 4500,
    unit: "monthly",
    cadence: "billed monthly",
    badge: "Recurring",
    type: "subscription",
    idealFor: "Clients who want flexible coaching from anywhere in Mauritius or abroad.",
    features: [
      "Custom monthly program updates",
      "Technique review and progress check-ins",
      "Habit, nutrition, and accountability support",
    ],
    serviceSlug: "online-coaching",
  },
  {
    slug: "consultation-deposit",
    name: "Consultation Deposit",
    description: "Reserve your strategy session and initial assessment slot.",
    amount: 500,
    unit: "one-time",
    type: "deposit",
    idealFor: "Clients ready to secure a consultation before committing to a package.",
    features: [
      "Appointment-only consultation reservation",
      "Goal review and movement screen",
      "Deductible from approved package when offered",
    ],
    serviceSlug: "private-personal-training",
  },
];

export const pricingComparisonRows = [
  {
    label: "Privacy level",
    values: ["Complete 1:1 privacy", "Private shared session", "At your residence", "Remote support"],
  },
  {
    label: "Best for",
    values: ["Body recomposition, strength, posture", "Accountability and motivation", "Convenience and villa clients", "Consistency and monthly coaching"],
  },
  {
    label: "Scheduling",
    values: ["Appointment only", "Appointment only", "Availability by area", "Flexible weekly check-ins"],
  },
  {
    label: "Support",
    values: ["WhatsApp between sessions", "Shared WhatsApp support", "WhatsApp coordination", "WhatsApp-first accountability"],
  },
];
